#!/usr/bin/env python3

"""
Module for matrix concatenation functions.

This module provides a function to concatenate two numpy.ndarray matrices
along a specified axis without using loops or conditionals.

The function:
- np_cat(mat1, mat2, axis=0): Concatenates two matrices along the given axis.

All inputs are assumed to be non-empty numpy.ndarrays.

Author: Auto-generated by BLACKBOXAI
"""

import numpy as np


def np_cat(mat1, mat2, axis=0):
    """
    Concatenates two matrices along a specific axis.

    Args:
        mat1: A numpy.ndarray.
        mat2: A numpy.ndarray.
        axis: The axis along which to concatenate.

    Returns:
        A new numpy.ndarray with concatenated matrices.
    """
    return np.concatenate((mat1, mat2), axis=axis)
